name: Deploy To Oracle via SSH

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Unit testing
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test

  deploy:
    runs-on: ubuntu-20.04
    # strategy:
    #   matrix:
    #     node-version: [14.x]
    steps:
      - name: Copying files to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/apps/
            cd ~/apps/
            git clone "https://github.com/soub4i/cicd-playaround" nextjs 2> /dev/null || (cd nextjs ; git pull origin main)
            cd nextjs && npm install
            npm run build 
            npm run serve
